//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Office2003Style.rc
//
#define IDD_ABOUTBOX				100
#define IDP_OLE_INIT_FAILED			100
#define IDR_POPUP_EDIT				119
#define ID_STATUSBAR_PANE1			120
#define ID_STATUSBAR_PANE2			121
#define IDS_STATUS_PANE1			122
#define IDS_STATUS_PANE2			123
#define IDS_TOOLBAR_STANDARD		124
#define IDS_TOOLBAR_CUSTOMIZE		125
#define ID_VIEW_CUSTOMIZE			126
#define IDR_MAINFRAME				128
#define IDR_MAINFRAME_256			129
#define IDR_Office2003StyleTYPE				130
#define ID_VIEW_NAVIGATION			185
#define IDB_NAVIGATION_LARGE		186
#define IDB_NAVIGATION_LARGE_HC		187
#define IDB_PAGES					188
#define IDB_PAGES_HC				189
#define IDB_PAGES_SMALL				190
#define IDB_PAGES_SMALL_HC			191
#define ID_TOOLS_OPTIONS			220
#define ID_VIEW_CAPTION_BAR			221
#define IDB_INFO					230
#define IDS_CAPTION_BUTTON			231
#define IDS_CAPTION_BUTTON_TIP		232
#define IDS_CAPTION_TEXT			233
#define IDS_CAPTION_IMAGE_TIP		234
#define IDS_CAPTION_IMAGE_TEXT		235
#define IDS_MYCALENDARS				250
#define IDS_CALENDAR				251
#define IDS_SHORTCUTS				252
#define IDS_FOLDERS					253
#define IDS_OUTLOOKBAR				258
#define IDS_RIBBON_CAPTIONBAR		295
#define IDS_EDIT_MENU				306

// 다음은 새 개체에 사용할 기본값입니다.
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE	310
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		310
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
